# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Test
on: push
env:
  PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
  TOKEN: ${{ secrets.TOKEN }}
  ADMIN: ${{ secrets.ADMIN }}
  CLOUDINARY_API_KEY: ${{ secrets.CLOUDINARY_API_KEY }}
  CLOUDINARY_API_SECRET: ${{ secrets.CLOUDINARY_API_SECRET }}
  CLOUDINARY_NAME: ${{ secrets.CLOUDINARY_NAME }}

jobs:
  container-job:
    runs-on: ubuntu-latest
    container: node:16

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: 123456
          POSTGRES_USER: postgres
          POSTGRES_DB: test
          POSTGRES_PORT: 5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm ci

      - name: Testing Routes
        run: npm test
        env:
          TEST_DB_URL: postgres://reddit_test_user:root@localhost:5432/reddit_test